# Generated by Django 5.0.6 on 2024-06-29 12:28

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos')),
                ('description', models.TextField(blank=True)),
                ('verification', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos')),
                ('description', models.TextField(blank=True)),
                ('verification', models.BooleanField(default=False)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('enrollment_no', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('semester', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('batch', models.CharField(max_length=3)),
                ('roll_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('job_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], default='Unemployed', max_length=10)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('salary', models.PositiveIntegerField()),
                ('deadline_to_apply', models.DateTimeField()),
                ('bond_period', models.CharField(max_length=20)),
                ('duration_of_job', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievEaseApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievEaseApp.hr')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrievEaseApp.jobposting')),
            ],
        ),
        migrations.AddField(
            model_name='hr',
            name='applied_postings',
            field=models.ManyToManyField(blank=True, to='GrievEaseApp.jobposting'),
        ),
    ]
